name: kcp
lang: go
lang_version: "1.25.7"
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: true
semaphore:
  enable: true
  pipeline_enable: false
  managed_sections:
    - version
    - name
    - agent
    - global_job_config
